### ISSUE TITLE
Would be nice to be able to override the Handler/Sender idents

### ISSUE THREAD

**Issue by neonphog** [holochain/ghost_actor#28]
something like?

```rust
ghost_actor::ghost_actor! {
    pub chan Bob {
        type Error = BobError;
        type Handler = BobHandler;
        type Sender = BobSender;
        
        fn msg() ...
    }
}
```

**Comment by maackle** [comment]
I know I suggested using "associated types" for all 3 but now that I think about it `Error` corresponds to a preexisting type, and the other two are generated based on the name you provide, so they are not all of the same ilk and might be good to have different syntax for each.

**Comment by neonphog** [comment]
```rust
ghost_chan! {
    pub chan Bob
    where
        HandlerName: BobHandler,
        SenderName: BobSender,
        ErrorType: BobError,
    {
        fn msg() ...
    }
}
```

It's certainly not idiomatic - it's not like these things are bounds... but the `Name` vs `Type` distinguishes things that already exist from things that will be generated...

**Comment by neonphog** [comment]
No longer relevant for v4-no-macro
